// Generated by CoffeeScript 1.8.0
(function() {
  this.Codewave.CmdInstance = (function() {
    function CmdInstance(codewave, pos, str) {
      this.codewave = codewave;
      this.pos = pos;
      this.str = str;
      this._checkCloser();
      this.noBracket = this._removeBracket(this.str);
      this._splitComponents();
      this._findClosing();
      this.cmd = this._getCmd();
    }

    CmdInstance.prototype._checkCloser = function() {
      var f, noBracket;
      noBracket = this._removeBracket(this.str);
      if (noBracket.substring(0, this.codewave.closeChar.length) === this.codewave.closeChar && (f = this._findOpeningPos())) {
        this.closingPos = {
          pos: this.pos,
          str: this.str
        };
        this.pos = f.pos;
        return this.str = f.str;
      }
    };

    CmdInstance.prototype._findOpeningPos = function() {
      var closing, cmdName, f, opening;
      cmdName = this._removeBracket(this.str).substring(this.codewave.closeChar.length);
      opening = this.codewave.brakets + cmdName;
      closing = this.str;
      if (f = this.codewave.findMatchingPair(this.pos, opening, closing, -1)) {
        f.str = this.codewave.editor.textSubstr(f.pos, this.codewave.findNextBraket(f.pos + f.str.length) + this.codewave.brakets.length);
        return f;
      }
    };

    CmdInstance.prototype._splitComponents = function() {
      var parts;
      parts = this.noBracket.split(" ");
      this.cmdName = parts.shift();
      return this._parseParams(parts);
    };

    CmdInstance.prototype._parseParams = function(params) {
      var key, p, parts, _i, _len, _results;
      this.params = [];
      this.named = {};
      _results = [];
      for (_i = 0, _len = params.length; _i < _len; _i++) {
        p = params[_i];
        parts = p.split(":");
        if (parts.length > 1) {
          key = parts.shift();
          _results.push(this.named[key] = parts.join(":"));
        } else {
          _results.push(this.params.push(p));
        }
      }
      return _results;
    };

    CmdInstance.prototype._findClosing = function() {
      var f;
      if (f = this._findClosingPos()) {
        this.content = this.codewave.editor.textSubstr(this.pos + this.str.length, f.pos).replace(/^\n/m, '').replace(/\n$/m, '');
        return this.str = this.codewave.editor.textSubstr(this.pos, f.pos + f.str.length);
      }
    };

    CmdInstance.prototype._findClosingPos = function() {
      var closing, f, opening;
      if (this.closingPos != null) {
        return this.closingPos;
      }
      closing = this.codewave.brakets + this.codewave.closeChar + this.cmdName + this.codewave.brakets;
      opening = this.codewave.brakets + this.cmdName;
      if (f = this.codewave.findMatchingPair(this.pos + this.str.length, opening, closing)) {
        return this.closingPos = f;
      }
    };

    CmdInstance.prototype._getCmd = function() {
      var cmd;
      cmd = Codewave.cmd[this.cmdName];
      if (typeof cmd === "function" && ((cmd.prototype.execute != null) || (cmd.prototype.result != null))) {
        return new cmd(this);
      } else {
        return cmd;
      }
    };

    CmdInstance.prototype._removeBracket = function(str) {
      return str.substring(this.codewave.brakets.length, str.length - this.codewave.brakets.length);
    };

    CmdInstance.prototype.getParam = function(names, def) {
      var n, _i, _len;
      if (typeof names === 'string') {
        names = [names];
      }
      for (_i = 0, _len = names.length; _i < _len; _i++) {
        n = names[_i];
        if (this.named[n] != null) {
          return this.named[n];
        }
        if (this.params[n] != null) {
          return this.params[n];
        }
      }
      return def;
    };

    CmdInstance.prototype.execute = function() {
      var r;
      if (this.cmd != null) {
        if (this.cmd.execute != null) {
          return this.cmd.execute(this);
        } else if ((r = this.result()) != null) {
          return this.replaceWith(r);
        }
      }
    };

    CmdInstance.prototype.result = function() {
      if (this.cmd.result != null) {
        if (typeof this.cmd.result === "function") {
          return this.cmd.result();
        } else {
          return this.cmd.result;
        }
      } else if (typeof this.cmd === 'string') {
        return this.cmd;
      } else if (typeof this.cmd === "function") {
        return this.cmd();
      }
    };

    CmdInstance.prototype.getEndPos = function() {
      return this.pos + this.str.length;
    };

    CmdInstance.prototype.getIndent = function() {
      return this.pos - this.codewave.findLineStart(this.pos);
    };

    CmdInstance.prototype.applyIndent = function(text) {
      return text.replace(/\n/g, "\n" + Array(this.getIndent() + 1).join(" "));
    };

    CmdInstance.prototype.replaceWith = function(text) {
      text = this.applyIndent(text);
      this.codewave.editor.spliceText(this.pos, this.getEndPos(), text);
      return this.codewave.editor.setCursorPos(this.pos + text.length);
    };

    return CmdInstance;

  })();

}).call(this);

//# sourceMappingURL=cmd_instance.js.map
