// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Codewave.Detector = (function() {
    function Detector(data) {
      this.data = data != null ? data : {};
    }

    Detector.prototype.detect = function(finder) {};

    return Detector;

  })();

  this.Codewave.LangDetector = (function(_super) {
    __extends(LangDetector, _super);

    function LangDetector() {
      return LangDetector.__super__.constructor.apply(this, arguments);
    }

    LangDetector.prototype.detect = function(finder) {
      var lang;
      if (finder.codewave != null) {
        lang = finder.codewave.editor.getLang();
        if (lang != null) {
          return lang.lower();
        }
      }
    };

    return LangDetector;

  })(Codewave.Detector);

}).call(this);

//# sourceMappingURL=detector.js.map
