// Generated by CoffeeScript 1.8.0
(function() {
  this.Codewave.Editor = (function() {
    function Editor() {
      this.namespace = null;
    }

    Editor.prototype.bindedTo = function(codewave) {};

    Editor.prototype.text = function(val) {
      throw "Not Implemented";
    };

    Editor.prototype.textCharAt = function(pos) {
      throw "Not Implemented";
    };

    Editor.prototype.textLen = function() {
      throw "Not Implemented";
    };

    Editor.prototype.textSubstr = function(start, end) {
      throw "Not Implemented";
    };

    Editor.prototype.insertTextAt = function(text, pos) {
      throw "Not Implemented";
    };

    Editor.prototype.spliceText = function(start, end, text) {
      throw "Not Implemented";
    };

    Editor.prototype.getCursorPos = function() {
      throw "Not Implemented";
    };

    Editor.prototype.setCursorPos = function(start, end) {
      if (end == null) {
        end = null;
      }
      throw "Not Implemented";
    };

    Editor.prototype.beginUndoAction = function() {};

    Editor.prototype.endUndoAction = function() {};

    Editor.prototype.getLang = function() {
      return null;
    };

    Editor.prototype.getEmmetContextObject = function() {
      return null;
    };

    Editor.prototype.allowMultiSelection = function() {
      return false;
    };

    Editor.prototype.setMultiSel = function(selections) {
      throw "Not Implemented";
    };

    Editor.prototype.getMultiSel = function() {
      throw "Not Implemented";
    };

    Editor.prototype.canListenToChange = function() {
      return false;
    };

    Editor.prototype.addChangeListener = function(callback) {
      throw "Not Implemented";
    };

    Editor.prototype.removeChangeListener = function(callback) {
      throw "Not Implemented";
    };

    return Editor;

  })();

}).call(this);

//# sourceMappingURL=editor.js.map
