// Generated by CoffeeScript 1.8.0
(function() {
  this.Codewave.init();

  this.Codewave.detect = function(target) {
    return new Codewave(new Codewave.TextAreaEditor(target));
  };

}).call(this);

//# sourceMappingURL=init.js.map
