// Generated by CoffeeScript 1.8.0
(function() {
  var __slice = [].slice;

  this.Codewave.logger = {
    log: function() {
      var args, msg, _i, _len, _results;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (window.console) {
        _results = [];
        for (_i = 0, _len = args.length; _i < _len; _i++) {
          msg = args[_i];
          _results.push(console.log(msg));
        }
        return _results;
      }
    }
  };

}).call(this);

//# sourceMappingURL=logger.js.map
