// Generated by CoffeeScript 1.9.0
(function() {
  this.Codewave.storage = new ((function() {
    function _Class() {}

    _Class.prototype.save = function(key, val) {
      return localStorage.setItem(this.fullKey(key), JSON.stringify(val));
    };

    _Class.prototype.load = function(key) {
      return JSON.parse(localStorage.getItem(this.fullKey(key)));
    };

    _Class.prototype.fullKey = function(key) {
      return 'CodeWave_' + key;
    };

    return _Class;

  })());

}).call(this);

//# sourceMappingURL=storage.js.map
