// Generated by CoffeeScript 1.8.0
(function() {
  this.Codewave.TextParser = (function() {
    function TextParser(_text) {
      this._text = _text;
    }

    TextParser.prototype.text = function(val) {
      if (val != null) {
        this._text = val;
      }
      return this._text;
    };

    TextParser.prototype.textCharAt = function(pos) {
      return this.text()[pos];
    };

    TextParser.prototype.textLen = function(pos) {
      return this.text().length;
    };

    TextParser.prototype.textSubstr = function(start, end) {
      return this.text().substring(start, end);
    };

    TextParser.prototype.insertTextAt = function(text, pos) {
      return this.text(this.text().substring(0, pos) + text + this.text().substring(pos, this.text().length));
    };

    TextParser.prototype.spliceText = function(start, end, text) {
      return this.text(this.text().slice(0, start) + (text || "") + this.text().slice(end));
    };

    return TextParser;

  })();

}).call(this);

//# sourceMappingURL=text_parser.js.map
